Refactor Page
jobrunr/jobrunr pull request #893
Opened 2023-12-08 15:34 UTC by auloin

2023-12-14 18:01 UTC, rdehuyss requested changes
Excellent work! Only small stuff. Thanks for your great work!

2023-12-15 10:59 UTC, auloin commented on core/src/main/java/org/jobrunr/server/zookeeper/tasks/ZooKeeperTask.java
> +                        UnresolvableConcurrentJobModificationException unresolvableConcurrentJobModificationException) {
Looks like an auto-formatting by intellij...

2023-12-15 11:47 UTC, auloin commented on core/src/main/java/org/jobrunr/storage/StorageProvider.java
> +    }
Used by `MigrateFromV5toV6Task`, added test to `StorageProviderTest`

2023-12-15 12:14 UTC, auloin commented on core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoDBStorageProvider.java
> +        jobCollection = jobrunrDatabase.getCollection(elementPrefixer(collectionPrefix, NAME), Document.class);
Re-added field provenance to all constants as otherwise it'd be too confusing to know and when not to statistically import field.

2023-12-19 11:57 UTC, rdehuyss approved these changes
LGTM!

2023-12-19 11:59 UTC, merged