Upgrade frontend packages
jobrunr/jobrunr pull request #917
Opened 2024-01-18 16:40 UTC by auloin

2024-01-20 23:43 UTC, rdehuyss requested changes
Great work. I love the `StatCard` and think we should use  a similar approach for the problems and the different state components.
I also have the impression that the overall font-size is smaller. Is that possible or is my eyesight getting worse 🤓?

I also noticed that if there are 2 warnings and an error in the dashboard and I dismiss only one warning, the 2 of them are gone. I also think the error should go on top.

I would also like to add eslint and prettier. However, since trying it, Intellij consumes all my CPU

2024-01-22 13:14 UTC, auloin commented
> I also have the impression that the overall font-size is smaller. Is that possible or is my eyesight getting worse 🤓?

I checked with chrome font-sizes are still the same.

> I also noticed that if there are 2 warnings and an error in the dashboard and I dismiss only one warning, the 2 of them are gone. I also think the error should go on top.
> 
Should be fixed.

2024-01-22 15:24 UTC, auloin commented on core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/jobs/job-view.js
> +                                        size="large"><SortAscending/></IconButton>
I simplified it without creating a new component

2024-01-22 16:03 UTC, auloin commented on core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/jobs/job-view.js
> +            navigate(-1);
Is this still necessary?

2024-01-23 16:15 UTC, rdehuyss approved these changes

2024-01-23 17:05 UTC, merged